### ISSUE TITLE
Container names re-randomized upon host restart

### ISSUE THREAD

**Issue by beardicus** [Flink/dokku-named-containers#1]
Hi!

I've just started playing with docker/dokku, so I'm having trouble debugging this in a useful way. I'm running dokku from the digital ocean prebuilt image, dokku 0.4.1, docker verison 1.8.2.

The plugin works as described, but when I restart the host machine, the container name is reset to the usual randomized docker name. Rebuilding or restarting the app fixes it.

Any thoughts? Thanks!

**Comment by Flink** [comment]
Are you sure? I just tested this with the dokku vagrant VM and what I saw is that just after docker boot, containers don’t always have their names but after a while (seconds/minutes) their random names are replaced correctly. This is I think because I’m replacing containers names in a `post-deploy` hook and after a host reboot containers are redeployed so while they’re not completely redeployed their name isn’t replaced.

**Comment by beardicus** [comment]
Tested again this morning. After an hour the container name is still random:

```
root@dokku:~# docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS               NAMES
a9d4fbaabcd6        dokku/test-app:latest   "/start web"        8 days ago          Up 8 days                               test-app.web.1
root@dokku:~# reboot

[...]

root@dokku:~# docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS               NAMES
47ea05ead0b6        dokku/test-app:latest   "/start web"        2 minutes ago       Up 2 minutes                            suspicious_bardeen
root@dokku:~# docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS               NAMES
47ea05ead0b6        dokku/test-app:latest   "/start web"        About an hour ago   Up About an hour                        suspicious_bardeen
root@dokku:~# 
```

**Comment by Flink** [comment]
Hmmm strange indeed. Could you try with latest master of dokku (and remove my plugin before updating) since it has been merged as core plugin and I think I made some changes.

**Comment by beardicus** [comment]
Sure thing. I'll try to tinker with it sometime this weekend.

**Comment by beardicus** [comment]
Uninstalled the plugin, updated to the current master branch (`v0.4.1-28-g8b21b5d`), rebuilt the app, rebooted, and the `test-app.web.1` container name stuck just fine. Thanks!

**Comment by Flink** [comment]
Great! :)
